# Generated by Django 4.2.28 on 2026-02-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descuento_puntos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
