# Generated by Django 4.2.28 on 2026-03-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_descuento_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud de la ubicación de entrega', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud de la ubicación de entrega', max_digits=9, null=True),
        ),
    ]
