# Generated by Django 4.2.28 on 2026-02-25 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('D', 'Descuento'), ('P', 'Producto Gratis'), ('E', 'Evento Exclusivo'), ('O', 'Otro')], default='D', max_length=1)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de descuento (solo para tipo Descuento)', max_digits=5, null=True)),
                ('nivel_minimo', models.IntegerField(default=1, help_text='Nivel mínimo de fidelización requerido')),
                ('puntos_necesarios', models.IntegerField(default=0, help_text='Puntos necesarios para canjear')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='beneficios/')),
                ('cupos', models.IntegerField(blank=True, help_text='Límite de beneficiarios', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto_regalo', models.ForeignKey(blank=True, help_text='Producto de regalo (solo para tipo Producto Gratis)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficios_regalo', to='menu.producto')),
            ],
            options={
                'verbose_name': 'Beneficio',
                'verbose_name_plural': 'Beneficios',
                'ordering': ['nivel_minimo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='NivelFidelidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(unique=True)),
                ('puntos_minimos', models.IntegerField()),
                ('puntos_maximos', models.IntegerField(blank=True, null=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descripcion', models.TextField()),
                ('beneficios_especiales', models.TextField(blank=True)),
                ('color', models.CharField(default='#FFD700', help_text='Color hexadecimal para el nivel', max_length=7)),
            ],
            options={
                'verbose_name': 'Nivel de Fidelización',
                'verbose_name_plural': 'Niveles de Fidelización',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('puntos_necesarios', models.IntegerField()),
                ('stock', models.IntegerField(default=0, help_text='Cantidad disponible')),
                ('activa', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recompensas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
                'ordering': ['puntos_necesarios'],
            },
        ),
        migrations.CreateModel(
            name='CanjeRecompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_canjeados', models.IntegerField()),
                ('fecha_canje', models.DateTimeField(auto_now_add=True)),
                ('entregado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes_recompensas', to='usuarios.perfil')),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to='fidelizacion.recompensa')),
            ],
            options={
                'verbose_name': 'Canje de Recompensa',
                'verbose_name_plural': 'Canjes de Recompensas',
                'ordering': ['-fecha_canje'],
            },
        ),
        migrations.CreateModel(
            name='CanjeBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_canjeados', models.IntegerField()),
                ('fecha_canje', models.DateTimeField(auto_now_add=True)),
                ('utilizado', models.BooleanField(default=False)),
                ('codigo_canje', models.CharField(max_length=20, unique=True)),
                ('notas', models.TextField(blank=True)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to='fidelizacion.beneficio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to='usuarios.perfil')),
            ],
            options={
                'verbose_name': 'Canje de Beneficio',
                'verbose_name_plural': 'Canjes de Beneficios',
                'ordering': ['-fecha_canje'],
            },
        ),
        migrations.CreateModel(
            name='Referido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_otorgados', models.IntegerField(default=0)),
                ('puntos_referido', models.IntegerField(default=0)),
                ('fecha_referido', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referidos_hechos', to='usuarios.perfil')),
                ('referido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referidos_recibidos', to='usuarios.perfil')),
            ],
            options={
                'verbose_name': 'Referido',
                'verbose_name_plural': 'Referidos',
                'unique_together': {('cliente', 'referido')},
            },
        ),
    ]
