# Generated by Django 4.2.28 on 2026-02-27 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fidelizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('P', 'Porcentaje'), ('F', 'Fijo')], default='P', max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Porcentaje o valor fijo', max_digits=10)),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Valor minimo de compra para aplicar', max_digits=10)),
                ('usos_maximos', models.IntegerField(default=1, help_text='Usos maximos del cupon')),
                ('usos_actuales', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cupon',
                'verbose_name_plural': 'Cupones',
            },
        ),
        migrations.RemoveField(
            model_name='canjebeneficio',
            name='beneficio',
        ),
        migrations.RemoveField(
            model_name='canjebeneficio',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='canjerecompensa',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='canjerecompensa',
            name='recompensa',
        ),
        migrations.DeleteModel(
            name='NivelFidelidad',
        ),
        migrations.AlterUniqueTogether(
            name='referido',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='referido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='referido',
            name='referido',
        ),
        migrations.AlterModelOptions(
            name='beneficio',
            options={'verbose_name': 'Beneficio', 'verbose_name_plural': 'Beneficios'},
        ),
        migrations.RemoveField(
            model_name='beneficio',
            name='cupos',
        ),
        migrations.RemoveField(
            model_name='beneficio',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='beneficio',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='beneficio',
            name='producto_regalo',
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='nivel_minimo',
            field=models.IntegerField(default=1, help_text='Nivel minimo requerido'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento', max_digits=5),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='tipo',
            field=models.CharField(choices=[('D', 'Descuento'), ('P', 'Producto Gratis'), ('E', 'Evento Especial')], default='D', max_length=1),
        ),
        migrations.DeleteModel(
            name='CanjeBeneficio',
        ),
        migrations.DeleteModel(
            name='CanjeRecompensa',
        ),
        migrations.DeleteModel(
            name='Recompensa',
        ),
        migrations.DeleteModel(
            name='Referido',
        ),
    ]
