# Generated by Django 4.2.28 on 2026-02-27 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('fidelizacion', '0002_cupon_remove_canjebeneficio_beneficio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficio',
            options={'ordering': ['puntos_necesarios'], 'verbose_name': 'Beneficio', 'verbose_name_plural': 'Beneficios'},
        ),
        migrations.AddField(
            model_name='beneficio',
            name='cantidad_producto',
            field=models.IntegerField(default=1, help_text='Cantidad del producto gratis'),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='producto_gratis',
            field=models.ForeignKey(blank=True, help_text='Producto que se regalará (para productos/entradas/bebidas gratis)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficios_producto', to='menu.producto'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='tipo',
            field=models.CharField(choices=[('D', 'Descuento'), ('P', 'Producto Gratis'), ('E', 'Evento Especial'), ('B', 'Bebida Gratis'), ('E', 'Entrada Gratis')], default='D', max_length=1),
        ),
    ]
