# Generated by Django 4.2.28 on 2026-02-25 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('NIT', 'NIT')], default='CC', max_length=3)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('direccion', models.TextField(blank=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('tipo_cliente', models.CharField(choices=[('F', 'Frecuente'), ('O', 'Ocasional'), ('VIP', 'VIP - Cliente Premium')], default='O', max_length=3)),
                ('puntos_fidelidad', models.IntegerField(default=0)),
                ('nivel_fidelidad', models.IntegerField(default=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_pedido', models.DateTimeField(blank=True, null=True)),
                ('total_pedidos', models.IntegerField(default=0)),
                ('gasto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
