# Generated by Django 4.2.28 on 2026-03-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cupones_usados',
            field=models.JSONField(blank=True, default=list, help_text='Lista de códigos de cupones ya utilizados'),
        ),
    ]
