# Generated by Django 4.2.28 on 2026-03-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_cupones_usados'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='direccion_latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud de la dirección guardada', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='direccion_longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud de la dirección guardada', max_digits=9, null=True),
        ),
    ]
