# Generated by Django 4.2.28 on 2026-02-25 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_producto', models.CharField(choices=[('B', 'Bebida'), ('A', 'Acompañamiento'), ('P', 'Plato Principal'), ('D', 'Postre'), ('O', 'Otro')], default='P', max_length=1)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('disponible', models.BooleanField(default=True)),
                ('vegetariano', models.BooleanField(default=False)),
                ('vegano', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('picantes', models.IntegerField(default=0)),
                ('tiempo_preparacion', models.IntegerField(default=15)),
                ('alergenos', models.TextField(blank=True, help_text='Lista de alérgenos separados por coma')),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='menu.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento', max_digits=5)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='promociones/')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('productos', models.ManyToManyField(related_name='promociones', to='menu.producto')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MenuDelDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('precio_especial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('bebida', models.ForeignKey(limit_choices_to={'tipo_producto': 'B'}, on_delete=django.db.models.deletion.PROTECT, related_name='menu_bebida', to='menu.producto')),
                ('entrada', models.ForeignKey(limit_choices_to={'tipo_producto__in': ['A', 'O']}, on_delete=django.db.models.deletion.PROTECT, related_name='menu_entrada', to='menu.producto')),
                ('plato_principal', models.ForeignKey(limit_choices_to={'tipo_producto': 'P'}, on_delete=django.db.models.deletion.PROTECT, related_name='menu_principal', to='menu.producto')),
                ('postre', models.ForeignKey(limit_choices_to={'tipo_producto': 'D'}, on_delete=django.db.models.deletion.PROTECT, related_name='menu_postre', to='menu.producto')),
            ],
            options={
                'verbose_name': 'Menú del Día',
                'verbose_name_plural': 'Menús del Día',
                'ordering': ['-fecha'],
            },
        ),
    ]
